In [1]:
import requests
import pandas as pd
import numpy as np
from datetime import datetime

In [33]:
url = 'https://www.cbp.gov/sites/default/files/assets/documents/2023-Jul/Daily_Currency_Notice_07-24-2023.xlsx'
response = requests.get(url)

In [34]:
if response.status_code == 200:
    with open('data.xlsx', 'wb') as f:
        f.write(response.content)
else:
    print("Failed to download the file")

In [35]:
df = pd.read_excel('data.xlsx', sheet_name='Daily Currency')
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,FOREIGN CURRENCY EXCHANGE RATE MULTIPLIERS,NaN,NaN,NaN,NaN
3,NaN,2023-07-24 00:00:00,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,ISO Code,Country/Union,Rate,IND,CUR Code
6,NaN,AU,AUSTRALIA,0.6678,Q,AUD
7,NaN,AT,AUSTRIA,0.080543,D,ATS
8,NaN,BE,BELGIUM,0.027474,D,BEF
9,NaN,BR,BRAZIL,0.208768,Q,BRL
10,NaN,CA,CANADA,0.755116,Q,CAD
11,NaN,CN,CHINA (MAINLAND),0.138122,Q,CNY
12,NaN,TW,CHINA (TAIWAN),0.031888,D,TWD
13,NaN,DK,DENMARK,0.146604,Q,DKK
14,NaN,EU,EUROPEAN UNION,1.1083,D,EUR
15,NaN,FI,FINLAND,0.186403,D,FIM
16,NaN,FR,FRANCE,0.168959,D,FRF
17,NaN,DE,GERMANY,0.566665,D,DEM
18,NaN,GR,GREECE,0.003253,D,GRD
19,NaN,HK,HONG KONG,0.127654,Q,HKD
20,NaN,IN,INDIA,0.012201,Q,INR
21,NaN,IR,IRAN,NaN,N,IRR
22,NaN,IE,IRELAND,1.407251,D,IEP
23,NaN,IL,ISRAEL,0.27371,D,ILS
24,NaN,IT,ITALY,0.000572,D,ITL
25,NaN,JP,JAPAN,0.00692,Q,JPY
26,NaN,KR,KOREA (SOUTH),0.000781,D,KRW
27,NaN,LU,LUXEMBOURG,0.027474,D,LUF
28,NaN,MY,MALAYSIA,0.214362,Q,MYR
29,NaN,MX,MEXICO,0.058624,Q,MXN
30,NaN,NL,NETHERLANDS,0.502925,D,NLG
31,NaN,NZ,NEW ZEALAND,0.6155,Q,NZD
32,NaN,NO,NORWAY,0.099438,Q,NOK
33,NaN,PH,PHILIPPINES,0.018109,Q,PHP
34,NaN,PT,PORTUGAL,0.005528,D,PTE
35,NaN,SG,SINGAPORE,0.740905,Q,SGD
36,NaN,ZA,SOUTH AFRICA,0.056401,Q,ZAR
37,NaN,ES,SPAIN,0.006661,D,ESP
38,NaN,LK,SRI LANKA,0.00304,Q,LKR
39,NaN,SE,SWEDEN,0.092379,Q,SEK
40,NaN,CH,SWITZERLAND,1.11657,Q,CHF
41,NaN,TH,THAILAND,0.028588,Q,THB
42,NaN,GB,UNITED KINGDOM,1.2695,Q,GBP
43,NaN,VE,VENEZUELA,0.03458,D,VES
44,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,The website www.cbp.gov is the official source...,NaN,NaN,NaN,NaN

In [36]:
df = df[df.columns[1:]]
df = df.dropna()
df.columns = df.iloc[0]
df = df[1:]
df.reset_index(drop=True, inplace=True)
df

5  ISO Code     Country/Union      Rate IND CUR Code
0        AU         AUSTRALIA    0.6678   Q      AUD
1        AT           AUSTRIA  0.080543   D      ATS
2        BE           BELGIUM  0.027474   D      BEF
3        BR            BRAZIL  0.208768   Q      BRL
4        CA            CANADA  0.755116   Q      CAD
5        CN  CHINA (MAINLAND)  0.138122   Q      CNY
6        TW    CHINA (TAIWAN)  0.031888   D      TWD
7        DK           DENMARK  0.146604   Q      DKK
8        EU    EUROPEAN UNION    1.1083   D      EUR
9        FI           FINLAND  0.186403   D      FIM
10       FR            FRANCE  0.168959   D      FRF
11       DE           GERMANY  0.566665   D      DEM
12       GR            GREECE  0.003253   D      GRD
13       HK         HONG KONG  0.127654   Q      HKD
14       IN             INDIA  0.012201   Q      INR
15       IE           IRELAND  1.407251   D      IEP
16       IL            ISRAEL   0.27371   D      ILS
17       IT             ITALY  0.000572   D      ITL
18       JP             JAPAN   0.00692   Q      JPY
19       KR     KOREA (SOUTH)  0.000781   D      KRW
20       LU        LUXEMBOURG  0.027474   D      LUF
21       MY          MALAYSIA  0.214362   Q      MYR
22       MX            MEXICO  0.058624   Q      MXN
23       NL       NETHERLANDS  0.502925   D      NLG
24       NZ       NEW ZEALAND    0.6155   Q      NZD
25       NO            NORWAY  0.099438   Q      NOK
26       PH       PHILIPPINES  0.018109   Q      PHP
27       PT          PORTUGAL  0.005528   D      PTE
28       SG         SINGAPORE  0.740905   Q      SGD
29       ZA      SOUTH AFRICA  0.056401   Q      ZAR
30       ES             SPAIN  0.006661   D      ESP
31       LK         SRI LANKA   0.00304   Q      LKR
32       SE            SWEDEN  0.092379   Q      SEK
33       CH       SWITZERLAND   1.11657   Q      CHF
34       TH          THAILAND  0.028588   Q      THB
35       GB    UNITED KINGDOM    1.2695   Q      GBP
36       VE         VENEZUELA   0.03458   D      VES

In [37]:
file_path = r'C:\Users\MOHAN_E0313\Downloads\CDR_CURRENCY_CONVERSION_CUSTOMS_072423.xlsx'
df2 = pd.read_excel(file_path, sheet_name = 'Sheet1' )

df2

,COUNTRY_CODE,COUNTRY_CODE FROM,CURRENCY_FROM,CURRENCY_TO,Rate,RATE_TYPE,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE,STATUS
0,US,AT,ATS,USD,0.080812,D,2023-07-21,2023-07-21,Y
1,US,AU,AUD,USD,0.667800,D,2023-07-21,2023-07-21,Y
2,US,BE,BEF,USD,0.027566,D,2023-07-21,2023-07-21,Y
3,US,BR,BRL,USD,0.208768,D,2023-07-21,2023-07-21,Y
4,US,CA,CAD,USD,0.755116,D,2023-07-21,2023-07-21,Y
5,US,CH,CHF,USD,1.116570,D,2023-07-21,2023-07-21,Y
6,US,CN,CNY,USD,0.138122,D,2023-07-21,2023-07-21,Y
7,US,DE,DEM,USD,0.568557,D,2023-07-21,2023-07-21,Y
8,US,DK,DKK,USD,0.146604,D,2023-07-21,2023-07-21,Y
9,US,ES,ESP,USD,0.006683,D,2023-07-21,2023-07-21,Y
10,US,EU,EUR,USD,1.112000,D,2023-07-21,2023-07-21,Y
11,US,FI,FIM,USD,0.187025,D,2023-07-21,2023-07-21,Y
12,US,FR,FRF,USD,0.169523,D,2023-07-21,2023-07-21,Y
13,US,GB,GBP,USD,1.269500,D,2023-07-21,2023-07-21,Y
14,US,GR,GRD,USD,0.003263,D,2023-07-21,2023-07-21,Y
15,US,HK,HKD,USD,0.127654,D,2023-07-21,2023-07-21,Y
16,US,IE,IEP,USD,1.411949,D,2023-07-21,2023-07-21,Y
17,US,IL,ILS,USD,0.276381,D,2023-07-21,2023-07-21,Y
18,US,IN,INR,USD,0.012201,D,2023-07-21,2023-07-21,Y
19,US,IT,ITL,USD,0.000574,D,2023-07-21,2023-07-21,Y
20,US,JP,JPY,USD,0.006920,D,2023-07-21,2023-07-21,Y
21,US,KR,KRW,USD,0.000779,D,2023-07-21,2023-07-21,Y
22,US,LK,LKR,USD,0.003063,D,2023-07-21,2023-07-21,Y
23,US,LU,LUF,USD,0.027566,D,2023-07-21,2023-07-21,Y
24,US,MX,MXN,USD,0.058624,D,2023-07-21,2023-07-21,Y
25,US,MY,MYR,USD,0.214362,D,2023-07-21,2023-07-21,Y
26,US,NL,NLG,USD,0.504604,D,2023-07-21,2023-07-21,Y
27,US,NO,NOK,USD,0.099156,D,2023-07-21,2023-07-21,Y
28,US,NZ,NZD,USD,0.615500,D,2023-07-21,2023-07-21,Y
29,US,PH,PHP,USD,0.018109,D,2023-07-21,2023-07-21,Y
30,US,PT,PTE,USD,0.005547,D,2023-07-21,2023-07-21,Y
31,US,SE,SEK,USD,0.092379,D,2023-07-21,2023-07-21,Y
32,US,SG,SGD,USD,0.740905,D,2023-07-21,2023-07-21,Y
33,US,TH,THB,USD,0.028588,D,2023-07-21,2023-07-21,Y
34,US,TW,TWD,USD,0.032000,D,2023-07-21,2023-07-21,Y
35,US,VE,VEF,USD,0.034580,D,2023-07-21,2023-07-21,Y
36,US,ZA,ZAR,USD,0.053346,D,2023-07-21,2023-07-21,Y

In [38]:
date_str = url.split('/')[-1].split('_')[-1].split('.')[0]
date = pd.to_datetime(date_str, format='%m-%d-%Y')

In [39]:
date = date.strftime('%d-%b-%y')
date

'24-Jul-23'

In [40]:
merged_table = pd.merge(df2, df, left_on='COUNTRY_CODE FROM', right_on='ISO Code', suffixes=('_df2', '_df'))

columns_to_drop = ['ISO Code', 'Country/Union', 'Rate_df2', 'IND', 'CUR Code']
 #Drop the additional C1 column from the merged DataFrame
merged_table.drop(columns_to_drop, axis=1, inplace=True)


# Define the new column name for the column you want to change
new_column_name = 'Rate'

# Assign the new column name to the specific column
merged_table.rename(columns={'Rate_df': new_column_name}, inplace=True)


# Define the desired order of columns
desired_order = ['COUNTRY_CODE', 'COUNTRY_CODE FROM', 'CURRENCY_FROM', 'CURRENCY_TO','Rate','RATE_TYPE','EFFECTIVE_FROM_DATE','EFFECTIVE_TO_DATE','STATUS']

# Rearrange the columns using reindex()
merged_table = merged_table.reindex(columns=desired_order)

merged_table

,COUNTRY_CODE,COUNTRY_CODE FROM,CURRENCY_FROM,CURRENCY_TO,Rate,RATE_TYPE,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE,STATUS
0,US,AT,ATS,USD,0.080543,D,2023-07-21,2023-07-21,NaN
1,US,AU,AUD,USD,0.6678,D,2023-07-21,2023-07-21,NaN
2,US,BE,BEF,USD,0.027474,D,2023-07-21,2023-07-21,NaN
3,US,BR,BRL,USD,0.208768,D,2023-07-21,2023-07-21,NaN
4,US,CA,CAD,USD,0.755116,D,2023-07-21,2023-07-21,NaN
5,US,CH,CHF,USD,1.11657,D,2023-07-21,2023-07-21,NaN
6,US,CN,CNY,USD,0.138122,D,2023-07-21,2023-07-21,NaN
7,US,DE,DEM,USD,0.566665,D,2023-07-21,2023-07-21,NaN
8,US,DK,DKK,USD,0.146604,D,2023-07-21,2023-07-21,NaN
9,US,ES,ESP,USD,0.006661,D,2023-07-21,2023-07-21,NaN
10,US,EU,EUR,USD,1.1083,D,2023-07-21,2023-07-21,NaN
11,US,FI,FIM,USD,0.186403,D,2023-07-21,2023-07-21,NaN
12,US,FR,FRF,USD,0.168959,D,2023-07-21,2023-07-21,NaN
13,US,GB,GBP,USD,1.2695,D,2023-07-21,2023-07-21,NaN
14,US,GR,GRD,USD,0.003253,D,2023-07-21,2023-07-21,NaN
15,US,HK,HKD,USD,0.127654,D,2023-07-21,2023-07-21,NaN
16,US,IE,IEP,USD,1.407251,D,2023-07-21,2023-07-21,NaN
17,US,IL,ILS,USD,0.27371,D,2023-07-21,2023-07-21,NaN
18,US,IN,INR,USD,0.012201,D,2023-07-21,2023-07-21,NaN
19,US,IT,ITL,USD,0.000572,D,2023-07-21,2023-07-21,NaN
20,US,JP,JPY,USD,0.00692,D,2023-07-21,2023-07-21,NaN
21,US,KR,KRW,USD,0.000781,D,2023-07-21,2023-07-21,NaN
22,US,LK,LKR,USD,0.00304,D,2023-07-21,2023-07-21,NaN
23,US,LU,LUF,USD,0.027474,D,2023-07-21,2023-07-21,NaN
24,US,MX,MXN,USD,0.058624,D,2023-07-21,2023-07-21,NaN
25,US,MY,MYR,USD,0.214362,D,2023-07-21,2023-07-21,NaN
26,US,NL,NLG,USD,0.502925,D,2023-07-21,2023-07-21,NaN
27,US,NO,NOK,USD,0.099438,D,2023-07-21,2023-07-21,NaN
28,US,NZ,NZD,USD,0.6155,D,2023-07-21,2023-07-21,NaN
29,US,PH,PHP,USD,0.018109,D,2023-07-21,2023-07-21,NaN
30,US,PT,PTE,USD,0.005528,D,2023-07-21,2023-07-21,NaN
31,US,SE,SEK,USD,0.092379,D,2023-07-21,2023-07-21,NaN
32,US,SG,SGD,USD,0.740905,D,2023-07-21,2023-07-21,NaN
33,US,TH,THB,USD,0.028588,D,2023-07-21,2023-07-21,NaN
34,US,TW,TWD,USD,0.031888,D,2023-07-21,2023-07-21,NaN
35,US,VE,VEF,USD,0.03458,D,2023-07-21,2023-07-21,NaN
36,US,ZA,ZAR,USD,0.056401,D,2023-07-21,2023-07-21,NaN

In [23]:
# Replace string representations with actual NaN values
Final_table = merged_table.replace({'NaN': np.nan, 'N/A': np.nan})

# Now you can use fillna() to replace NaNs with 'Y'
Final_table.fillna('Y', inplace=True)

Final_table.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37 entries, 0 to 36
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   COUNTRY_CODE         37 non-null     object
 1   COUNTRY_CODE FROM    37 non-null     object
 2   CURRENCY_FROM        37 non-null     object
 3   CURRENCY_TO          37 non-null     object
 4   Rate                 37 non-null     object
 5   RATE_TYPE            37 non-null     object
 6   EFFECTIVE_FROM_DATE  37 non-null     datetime64[ns]
 7   EFFECTIVE_TO_DATE    37 non-null     datetime64[ns]
 8   STATUS               37 non-null     object
dtypes: datetime64[ns](2), object(7)
memory usage: 2.9+ KB

In [41]:
Final_table['EFFECTIVE_FROM_DATE'] = date
Final_table['EFFECTIVE_TO_DATE'] = date

In [42]:
Final_table

,COUNTRY_CODE,COUNTRY_CODE FROM,CURRENCY_FROM,CURRENCY_TO,Rate,RATE_TYPE,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE,STATUS
0,US,AT,ATS,USD,0.080543,D,24-Jul-23,24-Jul-23,Y
1,US,AU,AUD,USD,0.6678,D,24-Jul-23,24-Jul-23,Y
2,US,BE,BEF,USD,0.027474,D,24-Jul-23,24-Jul-23,Y
3,US,BR,BRL,USD,0.208768,D,24-Jul-23,24-Jul-23,Y
4,US,CA,CAD,USD,0.755116,D,24-Jul-23,24-Jul-23,Y
5,US,CH,CHF,USD,1.11657,D,24-Jul-23,24-Jul-23,Y
6,US,CN,CNY,USD,0.138122,D,24-Jul-23,24-Jul-23,Y
7,US,DE,DEM,USD,0.566665,D,24-Jul-23,24-Jul-23,Y
8,US,DK,DKK,USD,0.146604,D,24-Jul-23,24-Jul-23,Y
9,US,ES,ESP,USD,0.006661,D,24-Jul-23,24-Jul-23,Y
10,US,EU,EUR,USD,1.1083,D,24-Jul-23,24-Jul-23,Y
11,US,FI,FIM,USD,0.186403,D,24-Jul-23,24-Jul-23,Y
12,US,FR,FRF,USD,0.168959,D,24-Jul-23,24-Jul-23,Y
13,US,GB,GBP,USD,1.2695,D,24-Jul-23,24-Jul-23,Y
14,US,GR,GRD,USD,0.003253,D,24-Jul-23,24-Jul-23,Y
15,US,HK,HKD,USD,0.127654,D,24-Jul-23,24-Jul-23,Y
16,US,IE,IEP,USD,1.407251,D,24-Jul-23,24-Jul-23,Y
17,US,IL,ILS,USD,0.27371,D,24-Jul-23,24-Jul-23,Y
18,US,IN,INR,USD,0.012201,D,24-Jul-23,24-Jul-23,Y
19,US,IT,ITL,USD,0.000572,D,24-Jul-23,24-Jul-23,Y
20,US,JP,JPY,USD,0.00692,D,24-Jul-23,24-Jul-23,Y
21,US,KR,KRW,USD,0.000781,D,24-Jul-23,24-Jul-23,Y
22,US,LK,LKR,USD,0.00304,D,24-Jul-23,24-Jul-23,Y
23,US,LU,LUF,USD,0.027474,D,24-Jul-23,24-Jul-23,Y
24,US,MX,MXN,USD,0.058624,D,24-Jul-23,24-Jul-23,Y
25,US,MY,MYR,USD,0.214362,D,24-Jul-23,24-Jul-23,Y
26,US,NL,NLG,USD,0.502925,D,24-Jul-23,24-Jul-23,Y
27,US,NO,NOK,USD,0.099438,D,24-Jul-23,24-Jul-23,Y
28,US,NZ,NZD,USD,0.6155,D,24-Jul-23,24-Jul-23,Y
29,US,PH,PHP,USD,0.018109,D,24-Jul-23,24-Jul-23,Y
30,US,PT,PTE,USD,0.005528,D,24-Jul-23,24-Jul-23,Y
31,US,SE,SEK,USD,0.092379,D,24-Jul-23,24-Jul-23,Y
32,US,SG,SGD,USD,0.740905,D,24-Jul-23,24-Jul-23,Y
33,US,TH,THB,USD,0.028588,D,24-Jul-23,24-Jul-23,Y
34,US,TW,TWD,USD,0.031888,D,24-Jul-23,24-Jul-23,Y
35,US,VE,VEF,USD,0.03458,D,24-Jul-23,24-Jul-23,Y
36,US,ZA,ZAR,USD,0.056401,D,24-Jul-23,24-Jul-23,Y

In [43]:

# Specify the path where you want to save the Excel file
excel_file_path = r'C:\Users\MOHAN_E0313\Downloads\CDR_CURRENCY_CONVERSION_CUSTOMS_new1_072523.xlsx'

# Export the DataFrame to Excel
Final_table.to_excel(excel_file_path, index=False)

print(f"Data exported to {excel_file_path} successfully.")

Data exported to C:\Users\MOHAN_E0313\Downloads\CDR_CURRENCY_CONVERSION_CUSTOMS_new1_072523.xlsx successfully.